name: 'Set Application URIs for Auth0'
description: 'Add & remove application URIs for Auth0 applications'
author: 'David Baumgold <david@davidbaumgold.com>'
branding:
  color: white
  icon: lock
inputs:
  milliseconds: # change this
    required: true
    description: 'input description here'
    default: 'default value if applicable'
runs:
  using: 'node16'
  main: 'dist/index.js'
